financeapp/urls.py
from django.urls import path, include
from . import views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('expenses/', views.ExpenseListView.as_view(), name='expense-all'),
    path('expense/<int:pk>', views.ExpenseDetailView.as_view(), name='expense-one'),
    path('allincome/', views.get_income, name='income-all'),
    path('income/<int:income_id>', views.get_single_income, name='income-one'),
    path('bills/', views.BillListView.as_view(), name='bill-all'),
    path('bill/<uuid:pk>', views.BillDetailView.as_view(), name='bill-one'),
    path('search/', views.search, name='search'),
    path('register/', views.register_user, name='register-url'),
    path('profile/', views.profile, name='profile-url'),
    path('allincome/new', views.IncomeCreateView.as_view(), name='income-new'),
    path('expenses/new', views.ExpenseCreateView.as_view(), name='expense-new'),
    path('bills/new', views.BillCreateView.as_view(), name='bill-new'),
    path('allincome/delete/<int:pk>', views.IncomeDeleteView.as_view(), name='income-delete'),
    path('allincome/update/<int:pk>', views.IncomeUpdateView.as_view(), name='income-update'),
    path('expenses/delete/<int:pk>', views.ExpenseDeleteView.as_view(), name='expense-delete'),
    path('expenses/update/<int:pk>', views.ExpenseUpdateView.as_view(), name='expense-update'),
    path('bills/delete/<uuid:pk>', views.BillDeleteView.as_view(), name='bill-delete'),
    path('bills/update/<uuid:pk>', views.BillUpdateView.as_view(), name='bill-update'),
    path('statisticsincome/', views.income_graph_view, name='statistics-income'),
    path('statisticsincome/monthly', views.income_graph_view_monthly, name='statistics-income-monthly'),
    path('statisticsincome/c1', views.income_graph_view_c1, name='statistics-income-c1'),
    path('statisticsincome/c2', views.income_graph_view_c2, name='statistics-income-c2'),
    path('statisticsincome/c3', views.income_graph_view_c3, name='statistics-income-c3'),
    path('statisticsincome/c4', views.income_graph_view_c4, name='statistics-income-c4'),
    path('statisticsexpense/', views.expenses_graph_view, name='statistics-expenses'),
    path('statisticsexpense/monthly', views.expenses_graph_view_monthly, name='statistics-expenses-monthly'),
    path('statisticsexpense/c1', views.expenses_graph_view_c1, name='statistics-expenses-c1'),
    path('statisticsexpense/c2', views.expenses_graph_view_c2, name='statistics-expenses-c2'),
    path('statisticsexpense/c3', views.expenses_graph_view_c3, name='statistics-expenses-c3'),
    path('statisticsexpense/c4', views.expenses_graph_view_c4, name='statistics-expenses-c4'),
    path('statisticsexpense/c5', views.expenses_graph_view_c5, name='statistics-expenses-c5'),
    path('statisticsbill/', views.bills_scatter_view, name='statistics-bills'),
    path('statisticsbill/c1', views.bills_scatter_view_c1, name='statistics-bill-c1'),
    path('statisticsbill/c2', views.bills_scatter_view_c2, name='statistics-bill-c2'),
    path('statisticsbill/c3', views.bills_scatter_view_c3, name='statistics-bill-c3'),
    path('statisticsbill/monthly', views.bills_scatter_view_monthly, name='statistics-bills-monthly'),
    path('reviews/', views.AppReviewListView.as_view(), name='reviews'),
    path('allincome/new/newcategory', views.IncomeCategoryModeratorCreateView.as_view(), name='income-category-new'),
    path('expenses/new/newcategory', views.ExpenseCategoryModeratorCreateView.as_view(), name='expense-category-new'),
    path('expenses/new/newcompany', views.CompanyModeratorCreateView.as_view(), name='expense-company-new'),
    path('bills/new/newcategory', views.BillCategoryModeratorCreateView.as_view(), name='bill-category-new'),
    path('bills/new/newissuer', views.BillIssuerModeratorCreateView.as_view(), name='bill-issuer-new'),
]

financepro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finance/', include('financeapp.urls')),
    path('', RedirectView.as_view(url='finance/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + [path('accounts/', include('django.contrib.auth.urls')),
     path('tinymce/', include('tinymce.urls'))]

financeapp/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from datetime import date
from PIL import Image
from tinymce.models import HTMLField


class IncomeCategory(models.Model):
    category = models.CharField('Category', max_length=100)

    class Meta:
        verbose_name = 'Income category'
        verbose_name_plural = 'Income categories'

    def __str__(self):
        return f"{self.category}"


class ExpenseCategory(models.Model):
    category = models.CharField('Category', max_length=100)

    class Meta:
        verbose_name = 'Expense category'
        verbose_name_plural = 'Expense categories'

    def __str__(self):
        return f"{self.category}"


class Income(models.Model):
    amount = models.IntegerField('Amount')
    date = models.DateField('Date')
    note = HTMLField(null=True, blank=True)
    income_category = models.ForeignKey(IncomeCategory, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ('date', 'amount')
        verbose_name = 'Income'
        verbose_name_plural = 'Income'

    @property
    def get_total_amount(self):
        income = Income.objects.all()
        total_amount = sum(row.amount for row in income)
        return total_amount

    def __str__(self):
        return f'{self.date} {self.amount} {self.note}'


class Company(models.Model):
    name = models.CharField('Name', max_length=100)
    address = models.CharField('Address', max_length=100)
    phone = models.CharField('Phone', max_length=100)
    email = models.CharField('Email', max_length=100)

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'

    def __str__(self):
        return f'{self.name} {self.address} {self.phone} {self.email}'


class Expense(models.Model):
    amount = models.IntegerField('Amount')
    date = models.DateField('Date')
    note = HTMLField(null=True, blank=True)
    pic = models.ImageField('Invoice', upload_to='pics', null=True, blank=True)
    expense_category = models.ManyToManyField(ExpenseCategory)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ('date', 'amount')

    def __str__(self):
        return f'{self.date} {self.amount} {self.note}'

    def display_categories(self):
        return ', '.join(elem.category for elem in self.expense_category.all())


class BillIssuer(models.Model):
    name = models.CharField('Name', max_length=100)
    address = models.CharField('Address', max_length=100)
    phone = models.CharField('Phone', max_length=100)
    email = models.CharField('Email', max_length=100)

    def __str__(self):
        return f'{self.name} {self.address} {self.phone} {self.email}'


class BillCategory(models.Model):
    category = models.CharField('Category', max_length=100)

    class Meta:
        verbose_name = 'Bill category'
        verbose_name_plural = 'Bill categories'

    def __str__(self):
        return f"{self.category}"


class Bill(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    amount = models.IntegerField('Amount')
    date_due = models.DateField('Date due')
    date_paid = models.DateField('Date paid', null=True, blank=True)
    note = HTMLField(null=True, blank=True)
    pic = models.ImageField('Bill', upload_to='pics', null=True, blank=True)
    bill_issuer = models.ForeignKey(BillIssuer, on_delete=models.CASCADE)
    bill_category = models.ForeignKey(BillCategory, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    BILL_STATUS = (
        ('u', 'Unpaid'),
        ('p', 'Paid on time'),
        ('o', 'Overdue'),
        ('l', 'Paid late')
    )

    status = models.CharField(
        max_length=1,
        choices=BILL_STATUS,
        blank=True,
        default='u',
        help_text='Bill status'
    )

    def __str__(self):
        return f"{self.date_due} {self.date_paid} {self.amount}"


class Profile(models.Model):
    picture = models.ImageField(upload_to='profile_pics', default='default.png')
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.picture.path)
        thumb_size = (200, 200)
        img.thumbnail(thumb_size)
        img.save(self.picture.path)


class AppReview(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Review', max_length=2000)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f'{self.date_created}, {self.reviewer}, {self.content[:50]}'

financeapp/forms.py
from django import forms

from .models import (Profile, User, Income, IncomeCategory, Expense, Company, ExpenseCategory, Bill, BillCategory,
                     BillIssuer, AppReview)


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('picture',)


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')


class DateInput(forms.DateInput):
    input_type = 'date'


class IncomeCreateForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ('amount', 'date', 'note', 'income_category', 'user')

        widgets = {
            'date': DateInput(),
            'user': forms.HiddenInput()
        }


class IncomeCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = IncomeCategory
        fields = ('category',)


class ExpenseCreateForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ('amount', 'date', 'company', 'expense_category', 'note', 'pic', 'user')

        widgets = {
            'user': forms.HiddenInput(),
            'date': DateInput()
        }


class CompanyCreateForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'address', 'phone', 'email')


class ExpenseCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ('category',)


class BillCreateForm(forms.ModelForm):
    class Meta:
        model = Bill
        fields = ('amount', 'date_due', 'date_paid', 'bill_category', 'bill_issuer', 'status', 'note', 'pic', 'user')

        widgets = {
            'user': forms.HiddenInput(),
            'date_due': DateInput(),
            'date_paid': DateInput()
        }


class BillIssuerCreateForm(forms.ModelForm):
    class Meta:
        model = BillIssuer
        fields = ('name', 'address', 'phone', 'email')


class BillCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = BillCategory
        fields = ('category',)


class AppReviewForm(forms.ModelForm):
    class Meta:
        model = AppReview
        fields = ('content', 'reviewer')
        widgets = {
            'reviewer': forms.HiddenInput()
        }

financeapp/templates/bill_delete.html
{% extends "base.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <fieldset class="form-group"><legend class="border-bottom mb-4">Are you sure you want to delete this bill?</legend>
    <p><b>ID: </b>{{ bill.id }}</p>
    <p><b>Date issued: </b>{{ bill.billing_date }}</p>
    <p><b>Date due: </b>{{ bill.date_due }}</p>
    <p><b>Amount: </b>{{ bill.amount }} Eur</p>
    <p><b>Category: </b>{{ bill.bill_category }}</p>
    <p><b>Bill issuer: </b>{{ bill.bill_issuer.name }}</p>
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Yes</button>
        <a class="btn btn-outline-secondary" href="{% url 'bill-all' %}">Cancel</a>
    </div>
</form>



{% endblock %}

financeapp/templates/expense_create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New expense</legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>

{% for group in user.groups.all %}
    {% if 'moderators' == group.name %}
<div class="form-group">
    <a class="btn btn-outline-info" href="{% url 'expense-category-new' %}">Create new category</a>
    <a class="btn btn-outline-info" href="{% url 'expense-company-new' %}">Create new company</a>
</div>
   {% endif %}
{% endfor %}

{% endblock %}

financeapp/templates/expense_delete.html
{% extends "base.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <fieldset class="form-group"><legend class="border-bottom mb-4">Are you sure you want to delete this expense?</legend>
    <p><b>Date: </b>{{ expense.date }}</p>
    <p><b>Amount: </b>{{ expense.amount }} Eur</p>
    <p><b>Company: </b>{{ expense.company.name }}</p>
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Yes</button>
        <a class="btn btn-outline-secondary" href="{% url 'expense-all' %}">Cancel</a>
    </div>
</form>

{% endblock %}

financeapp/templates/expenses.html
{% extends "base.html" %}
{% block content %}

<h1>Expenses</h1>
<hr>
{% for expense_obj in expense_list %}
<li>
<a href="{% url 'expense-one' expense_obj.id%}">{{ expense_obj.date }}, {{ expense_obj.amount }} Eur,
    {{ expense_obj.display_categories }}, {{ expense_obj.company.name }}</a>
</li>
{% endfor %}

<hr>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

financeapp/templates/income.html
{% extends "base.html" %}
{% block content %}

<h1>Income</h1>
<hr>
<p><b>Date: </b>{{ income_obj.date }}</p>
<p><b>Amount: </b>{{ income_obj.amount }} Eur</p>
<p><b>Category: </b>{{ income_obj.income_category }}</p>
<hr>
<p><b>Note: </b>{{ income_obj.note | safe}}</p>

<div>
    <a class="btn-secondary btn-sm" href="{% url 'income-update' income_obj.id %}">Edit</a>
    <a class="btn-danger btn-sm" href="{% url 'income-delete' income_obj.id %}">Delete</a>
</div>

{% endblock %}

financeapp/templates/index.html
{% extends "base.html" %}
{% block content %}

<h1>Welcome to MY FINANCE!</h1>

<p>{{ request.user }}</p>
<p>{{ num_visits }}</p>

{% endblock %}

financeapp/templates/moderator_company_create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New company</legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>

{% endblock %}

financeapp/templates/statistics_bill_c1.html
{% extends "base.html" %}
{% block content %}

<h1>Water</h1>
<h4><b>Total amount: </b>{{ total_amount }} Eur</h4>
<hr>
{% if chart %}
    <img src="data:image/png;base64, {{ chart | safe }}">
{% endif %}
<hr>
<a class="btn-secondary btn-sm" href="{% url 'statistics-bills' %}">Back</a>

{% endblock %}

financeapp/templates/statistics_bill_c2.html
{% extends "base.html" %}
{% block content %}

<h1>Electricity</h1>
<h4><b>Total amount: </b>{{ total_amount }} Eur</h4>
<hr>
{% if chart %}
    <img src="data:image/png;base64, {{ chart | safe }}">
{% endif %}
<hr>
<a class="btn-secondary btn-sm" href="{% url 'statistics-bills' %}">Back</a>

{% endblock %}

financeapp/templates/statistics_bill_monthly.html
{% extends "base.html" %}
{% block content %}

<h4><b>Total bill amount this month: </b>{{ total_amount_monthly }} Eur</h4>
<hr>
{% if chart %}
    <img src="data:image/png;base64, {{ chart | safe }}">
{% endif %}
<hr>
<a class="btn-secondary btn-sm" href="{% url 'statistics-bills' %}">Back</a>

{% endblock %}

financeapp/templates/statistics_expense_categories.html
{% extends "base.html" %}
{% block content %}

<hr>
{% if chart %}
    <img src="data:image/png;base64, {{ chart | safe }}">
{% endif %}
<hr>
<a class="btn-secondary btn-sm" href="{% url 'statistics-expenses' %}">Back</a>

{% endblock %}

financeapp/templates/statistics_income_c1.html
{% extends "base.html" %}
{% block content %}

<h1>Salary</h1>
<h4><b>Total amount: </b>{{ total_amount }} Eur</h4>
<hr>
{% if chart %}
    <img src="data:image/png;base64, {{ chart | safe }}">
{% endif %}
<hr>
<a class="btn-secondary btn-sm" href="{% url 'statistics-income' %}">Back</a>

{% endblock %}

financeapp/templates/statistics_income_c2.html
{% extends "base.html" %}
{% block content %}

<h1>Vinted</h1>
<h4><b>Total amount: </b>{{ total_amount }} Eur</h4>
<hr>
{% if chart %}
    <img src="data:image/png;base64, {{ chart | safe }}">
{% endif %}
<hr>
<a class="btn-secondary btn-sm" href="{% url 'statistics-income' %}">Back</a>

{% endblock %}

financeapp/templates/statistics_income_monthly.html
{% extends "base.html" %}
{% block content %}

<h4><b>Total income this month: </b>{{ total_amount_monthly }} Eur</h4>
<hr>
{% if chart %}
    <img src="data:image/png;base64, {{ chart | safe }}">
{% endif %}
<hr>
<a class="btn-secondary btn-sm" href="{% url 'statistics-income' %}">Back</a>

{% endblock %}